platform :ios, '9.0'
def pods
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDWebImage', '~> 3.8.1'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'Masonry'
end
target 'STHelperKit' do
pods
end
